[tool.black]
exclude = """
/(
   | .*migrations/.*.py
)/
"""

[tool.isort]
know_third_party = ["django"]

[tool.pytest.ini_options]
minversion = "6.0"
pythonpath = "b3_tracker"
python_files = "*test*.py"

DJANGO_SETTINGS_MODULE = "b3_tracker.settings"
addopts = "--cov=. --cov-branch --cov-report=xml:coverage/cov.xml"
