[tool.black]
exclude = """
/(
   | .*migrations/.*.py
)/
"""

[tool.isort]
know_third_party = ["django"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = "django"
pythonpaths = "django"
python_files = "*test*.py"

DJANGO_SETTINGS_MODULE = "b3_tracker.settings"
addopts = "--cov=. --cob-brach --cov-report=xml:coverage/cov.xml"
