# Generated by Django 4.2 on 2024-05-19 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "code",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "max_price",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "min_price",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "last_price",
                    models.DecimalField(decimal_places=3, max_digits=12, null=True),
                ),
                ("last_price_date", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradingTunnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bottom_value", models.DecimalField(decimal_places=3, max_digits=12)),
                ("top_value", models.DecimalField(decimal_places=3, max_digits=12)),
                ("interval", models.IntegerField()),
                ("assets", models.ManyToManyField(to="trading_tunnel_alerts.asset")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="trading_tunnel_alerts.asset",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "date")},
            },
        ),
    ]
